/* Autogenerated file, DO NOT EDIT */
#include "test_util.h"

TEST_CASE("conv_sigmoid_2x2")
{
    pt::Tensor in{2, 2, 1};
    in.setData({0.2015306949615478515625, 0.80272495746612548828125, 0.698147952556610107421875, 0.975408136844635009765625});

    pt::Tensor expected{1};
    expected.setData({0.3557874858379364013671875});

    testModel(in, expected, "conv_sigmoid_2x2", 1e-6f);
}
