/* Autogenerated file, DO NOT EDIT */
#include "test_util.h"

TEST_CASE("conv_softplus_2x2")
{
    pt::Tensor in{2, 2, 1};
    in.setData({0.4323687851428985595703125, 0.3490321338176727294921875, 0.0568080730736255645751953, 0.86621654033660888671875});

    pt::Tensor expected{1};
    expected.setData({-0.534806311130523681640625});

    testModel(in, expected, "conv_softplus_2x2", 1e-6f);
}
