/* Autogenerated file, DO NOT EDIT */
#include "test_util.h"

TEST_CASE("conv_hard_sigmoid_2x2")
{
    pt::Tensor in{2, 2, 1};
    in.setData({0.905426323413848876953125, 0.654684364795684814453125, 0.169010102748870849609375, 0.0306607149541378021240234});

    pt::Tensor expected{1};
    expected.setData({-0.791795432567596435546875});

    testModel(in, expected, "conv_hard_sigmoid_2x2", 1e-6f);
}
