/* Autogenerated file, DO NOT EDIT */
#include "test_util.h"

TEST_CASE("conv1d_3")
{
    pt::Tensor in{3, 1};
    in.setData({0.97535002231597900390625, 0.1679832935333251953125, 0.9727876186370849609375});

    pt::Tensor expected{1};
    expected.setData({0.0589166656136512756347656});

    testModel(in, expected, "conv1d_3", 1e-6f);
}
