/* Autogenerated file, DO NOT EDIT */
#include "test_util.h"

TEST_CASE("dense_1x1")
{
    pt::Tensor in{1};
    in.setData({0});

    pt::Tensor expected{1};
    expected.setData({0.0010000000474974513053894});

    testModel(in, expected, "dense_1x1", 1e-6f);
}
