/* Autogenerated file, DO NOT EDIT */
#include "test_util.h"

TEST_CASE("locally_connected_1d_2")
{
    pt::Tensor in{2, 1};
    in.setData({0.503065049648284912109375, 0.81314766407012939453125});

    pt::Tensor expected{1};
    expected.setData({-0.342222750186920166015625});

    testModel(in, expected, "locally_connected_1d_2", 1e-6f);
}
